Test1 = 0
for index in range(2):
    basic.show_string(":)")
    music.set_tempo(157)
    music.play_tone(523, music.beat(BeatFraction.WHOLE))
    music.play_tone(622, music.beat(BeatFraction.WHOLE))
    music.play_tone(698, music.beat(BeatFraction.WHOLE))
    music.play_tone(740, music.beat(BeatFraction.WHOLE))
    music.play_tone(698, music.beat(BeatFraction.WHOLE))
    music.play_tone(622, music.beat(BeatFraction.WHOLE))
    music.play_tone(523, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.DOUBLE))
    music.set_tempo(250)
    music.play_tone(466, music.beat(BeatFraction.WHOLE))
    music.play_tone(587, music.beat(BeatFraction.WHOLE))
    music.play_tone(523, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.DOUBLE))
    music.set_tempo(120)
    music.play_tone(196, music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.WHOLE))
    music.set_tempo(157)
    music.play_tone(523, music.beat(BeatFraction.WHOLE))
    music.play_tone(622, music.beat(BeatFraction.WHOLE))
    music.play_tone(698, music.beat(BeatFraction.WHOLE))
    music.play_tone(740, music.beat(BeatFraction.WHOLE))
    music.play_tone(698, music.beat(BeatFraction.WHOLE))
    music.play_tone(622, music.beat(BeatFraction.WHOLE))
    music.play_tone(740, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.DOUBLE))
    music.set_tempo(199)
    music.play_tone(740, music.beat(BeatFraction.WHOLE))
    music.play_tone(698, music.beat(BeatFraction.WHOLE))
    music.play_tone(622, music.beat(BeatFraction.WHOLE))
    music.play_tone(740, music.beat(BeatFraction.WHOLE))
    music.play_tone(698, music.beat(BeatFraction.WHOLE))
    music.play_tone(622, music.beat(BeatFraction.WHOLE))
    music.set_tempo(120)
    music.play_tone(262, music.beat(BeatFraction.DOUBLE))